[workspace]
resolver="2"

members = [
    "RIMPiler/command_line",
    "RIMPiler/frontend",
    "RIMPiler/backend",
    "regex",
    "utilities",
]

[profile.release]
opt-level = 3
strip = 'debuginfo'